apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete 
volumeBindingMode: WaitForFirstConsumer 
allowVolumeExpansion: true  
parameters:
  storageaccounttype: Standard_LRS 
  kind: managed 

  